/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * File Name: IntegerSum
 * Author: Leo Yang
 * Date: April 20, 2023
 * Description: Program that takes integers into an array, allows them to be listed
 * and can calculate the sum of the entered values and filter for odd and even
 */
import java.util.*;
import javax.swing.JOptionPane;
public class IntegerSum extends javax.swing.JFrame {
    private ArrayList<Integer> arr = new ArrayList(); // Creates new array
    private int size = 0; // creates a variable to help with adding new values to array
    private int sum; // creates variable for sum calc
    String[] options = {"List even", "List odd", "List all"}; // creates array of strings to store list options
    /**
     * Creates new form IntegerSum
     */
    public IntegerSum() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtEnterInt = new javax.swing.JLabel();
        inInt = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnSumAll = new javax.swing.JButton();
        btnSumEven = new javax.swing.JButton();
        btnSumOdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplay1 = new javax.swing.JTextArea();
        txtDisplay2 = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        txtTitle.setText("Integer Sums");

        txtEnterInt.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        txtEnterInt.setText("Enter an integer:");

        inInt.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 204, 204));
        btnRemove.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnList.setBackground(new java.awt.Color(166, 220, 255));
        btnList.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnSumAll.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnSumAll.setText("Sum All");
        btnSumAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumAllActionPerformed(evt);
            }
        });

        btnSumEven.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnSumEven.setText("Sum Even");
        btnSumEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumEvenActionPerformed(evt);
            }
        });

        btnSumOdd.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnSumOdd.setText("Sum Odd");
        btnSumOdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumOddActionPerformed(evt);
            }
        });

        txtDisplay1.setEditable(false);
        txtDisplay1.setColumns(20);
        txtDisplay1.setRows(5);
        jScrollPane2.setViewportView(txtDisplay1);

        txtDisplay2.setEditable(false);
        txtDisplay2.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        btnExit.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEnterInt)
                        .addGap(18, 18, 18)
                        .addComponent(inInt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDisplay2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSumAll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumEven, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumOdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterInt)
                    .addComponent(inInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSumAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSumEven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSumOdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);//closes program
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{//try catch statement to handle exceptions
         do{ // do while loop to handle increase array size with added values
            arr.add(Integer.parseInt(inInt.getText())); // add input to arr
            size ++; // add 1 to size
         }while(size < arr.size()); // continue loop while size is less than array size
         inInt.setText(""); // emptiy input field
     }catch(NumberFormatException e){ //if invalid entry, show error message
         JOptionPane.showMessageDialog(null, "Error, please enter an integer.");
     }   
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(inInt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error, please enter a value to remove.");// if user has not inputted value, prompt user to enter a value
        }else if(arr.isEmpty()){ // if the arr has no values
            JOptionPane.showMessageDialog(null, "List is empty, please add numbers.");//prompts user to add to arr
        }else{
            // for loop to find inputted variable
            for(int i = 0; i < arr.size(); i++){
              if(arr.get(i) == Integer.parseInt(inInt.getText())){ // check if any values = to one entered
              arr.remove(i); // if so, removes value
              size--; // subtract 1 from size if value is removed
              }
            }
         }
        inInt.setText(""); //empty input field
        displayArr(); // executes displays arr
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        if(arr.isEmpty()){//if the array is empty, run code
            JOptionPane.showMessageDialog(null, "Please add numbers to the list first.");//prompts user to add to list
        }else{
            txtDisplay1.setText(""); // empty txtDisplay1
            int chosenlist = JOptionPane.showOptionDialog(null, "What would you like to see from the list?", "List Type", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);//Creates int chosenlist to obtain information on option chosen to list from option string[]
            listOptions(chosenlist);
        } 
    }//GEN-LAST:event_btnListActionPerformed

    private void btnSumAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumAllActionPerformed
        for(int i : arr){//for loop to go through each value
            sum += i; // added to cumulative sum
        }
        txtDisplay2.setText("The sum of all values is "+String.valueOf(sum)); // converts the sum into a string and displays on txtDisplay2
        sum = 0; // reset sum
    }//GEN-LAST:event_btnSumAllActionPerformed

    private void btnSumEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumEvenActionPerformed
        for(int i = 0; i < arr.size(); i++){//for loop to go through each value
            if(arr.get(i) %2 == 0){ // obtain even values
                sum += arr.get(i); // added to cumulative sum
                txtDisplay2.setText("The sum of all even values is "+String.valueOf(sum)); // converts sum into string and displays
            }else{
                txtDisplay2.setText("No even values.");//if no even, state
            }
        }
        sum = 0; // resest sum
    }//GEN-LAST:event_btnSumEvenActionPerformed

    private void btnSumOddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumOddActionPerformed
        for(int i = 0; i < arr.size(); i++){//for looop to go throug values
            if(arr.get(i) %2 != 0){ // obtain odd values
                sum += arr.get(i); // added to sum
                txtDisplay2.setText("The sum of all odd numbers is "+String.valueOf(sum)); // converts sum into string and displays
            }else{
                txtDisplay2.setText("No odd values.");//if no odd, state
            }
        }
        sum = 0; // reset sum
    }//GEN-LAST:event_btnSumOddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegerSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegerSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegerSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegerSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegerSum().setVisible(true);
            }
        });
    }
    /*
     *@desc FUnction to display array
     */
    private void displayArr(){
        txtDisplay1.setText(""); // Empties txtDisplay1 in case of prior output
        for(int i = 0; i < arr.size(); i++){ //for loop to go get values
            txtDisplay1.setText(txtDisplay1.getText() + "\n" + arr.get(i).toString()); // displays array values
        }
    }
    
    /*
     *@desc Function to handle the different list options (even, odd, all). 
     */
    private void listOptions(int option){
        switch(option){
            case 0: // case for list even
                for(int i = 0; i < arr.size(); i++){ //for loop to find even numbers
                    if(arr.get(i) %2 == 0){ // If array element is even (remainder when divided by 2 = 0)
                        txtDisplay1.setText(txtDisplay1.getText() + "\n" + arr.get(i).toString()); // displays even numbers
                 }
                }
                break;
            case 1: // case for list even
                for(int i = 0; i < arr.size(); i++){ //for loop to find odd numbers
                    if(arr.get(i) %2 != 0){ // If array element is odd (remainder when divided by 2 != 0)
                        txtDisplay1.setText(txtDisplay1.getText() + "\n" + arr.get(i).toString()); //display odd
                 }
                }
                break;
            case 2: // case for list all
                displayArr(); // executes displayArr()
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSumAll;
    private javax.swing.JButton btnSumEven;
    private javax.swing.JButton btnSumOdd;
    private javax.swing.JTextField inInt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDisplay1;
    private javax.swing.JTextField txtDisplay2;
    private javax.swing.JLabel txtEnterInt;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
